// 事前に「REST Client」のvscode拡張機能入れとく

//*************** setting ***************//

@_apiurl = http://localhost:5000/api

//*************** setting ***************//

###***** GET *****###
GET {{_apiurl}}/posts HTTP/1.1

###***** GET BY ID *****###
GET {{_apiurl}}/posts/612612681f804ec8bf9c38ae HTTP/1.1

###***** POST *****###
POST {{_apiurl}}/posts
Content-Type: multipart/form-data; boundary="WebKitFormBoundary7MA4YWxkTrZu0gW"

--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

title01
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category"

category01
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"

content01
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="dummy_img01.png"
Content-Type: image/png

< ./uploads/dummy_img01.png
--WebKitFormBoundary7MA4YWxkTrZu0gW--

###***** PUT *****###
PUT {{_apiurl}}/posts/612612681f804ec8bf9c38ae HTTP/1.1
Content-Type: multipart/form-data; boundary="WebKitFormBoundary7MA4YWxkTrZu0gW"

--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

title01
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category"

category01
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"

content01
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="old_filename"

image_1629885056855_dummy_img02.png
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="dummy_img01.png"
Content-Type: image/png

< ./uploads/dummy_img01.png
--WebKitFormBoundary7MA4YWxkTrZu0gW--

###***** DELETE *****###
DELETE {{_apiurl}}/posts/612612681f804ec8bf9c38ae HTTP/1.1
